name: USDZ Conversion

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  convert:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Reality Converter
        run: |
          curl -L -o Reality_Converter_beta_5.dmg "https://developer.apple.com/augmented-reality/tools/files/Reality_Converter_beta_5.dmg"
          hdiutil attach Reality_Converter_beta_5.dmg
          cp -R "/Volumes/Reality Converter Beta 5/Reality Converter.app" /Applications
          hdiutil detach "/Volumes/Reality Converter Beta 5"

      - name: Prepare USDZCONVERT path
        run: |
          echo "USDZCONVERT_PATH='/Applications/Reality Converter.app/Contents/XPCServices/RealityConverterService.xpc/Contents/SharedSupport/usdpython/usdzconvert/usdzconvert'" >> $GITHUB_ENV

      - name: Convert USD to USDZ
        run: |
          export PYTHONPATH="/Applications/Reality Converter.app/Contents/XPCServices/RealityConverterService.xpc/Contents/SharedSupport/usdpython"
          $USDZCONVERT_PATH ./house.usd ./house_converted.usdz

      - name: Upload USDZ artifact
        uses: actions/upload-artifact@v4
        with:
          name: house_usdz
          path: house_converted.usdz
