name: USDZ Conversion (macOS, OpenUSD submodule)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-convert:
    runs-on: macos-15
    env:
      PYTHON_VERSION: "3.11"
    timeout-minutes: 60

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Verify files
        run: |
          ls -la
          test -f "$GITHUB_WORKSPACE/house.usd" || (echo "house.usd not found at repo root"; exit 1)
          test -f "$GITHUB_WORKSPACE/vendor/OpenUSD/build_scripts/build_usd.py" || (echo "OpenUSD submodule missing"; exit 1)

      - name: Restore cached OpenUSD (USDinst)
        id: cache-usd
        uses: actions/cache/restore@v4
        with:
          path: USDinst
          key: ${{ runner.os }}-OpenUSD-${{ env.PYTHON_VERSION }}-${{ hashFiles('vendor/OpenUSD/build_scripts/**/*') }}

      - name: Setup Python (only if building)
        if: steps.cache-usd.outputs.cache-hit != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install macOS build deps (only if building)
        if: steps.cache-usd.outputs.cache-hit != 'true'
        run: |
          export PATH=/Applications/CMake.app/Contents/bin:$PATH
          sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer
          python -m pip install --upgrade pip setuptools

      - name: Build OpenUSD (only if cache miss)
        if: steps.cache-usd.outputs.cache-hit != 'true'
        run: |
          set -e
          export PATH=/Applications/CMake.app/Contents/bin:$PATH
          python vendor/OpenUSD/build_scripts/build_usd.py \
            --no-materialx \
            --generator Xcode \
            --build USDgen/build \
            --src USDgen/src \
            USDinst \
            --build-args USD,"-DPXR_HEADLESS_TEST_MODE=ON -DPXR_BUILD_TESTS=OFF" -v | tee usd_build.log
          test -x USDinst/bin/usdzconvert || (echo "usdzconvert missing"; exit 1)

      - name: Save OpenUSD toolchain to cache
        if: steps.cache-usd.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: USDinst
          key: ${{ steps.cache-usd.outputs.cache-primary-key }}

      - name: Upload build log (always try)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: usd_build_log
          path: usd_build.log
          if-no-files-found: ignore

      - name: Sanity check tool
        run: |
          ls -la USDinst/bin
          USDinst/bin/usdzconvert --help >/dev/null

      - name: Convert USD -> USDZ
        run: |
          SRC="$GITHUB_WORKSPACE/house.usd"
          DST="$GITHUB_WORKSPACE/house.usdz"
          echo "Converting: $SRC -> $DST"
          USDinst/bin/usdzconvert "$SRC" "$DST"
          ls -lh "$DST"

      - name: Upload USDZ artifact
        uses: actions/upload-artifact@v4
        with:
          name: house_usdz
          path: house.usdz
